# Specify the docker image to use (only used if using docker runners)
# See: http://doc.gitlab.com/ee/ci/docker/using_docker_images.html
image: registry.gitlab.com/federicomarulli/cosmobolognalib 

compile_py2:
  tags:
  - astrotower
  script:
  # Compile our app
  - make 
  - make python
  - make allExamples
  - ./test.py nocompile nopy nodoc ALL
  artifacts:
    paths:
    - External
    - Examples
    - Headers/*.h
    - ./*.so
    - Python/CosmoBolognaLib.py
    - Python/_CosmoBolognaLib.so
    
compile_py3:
  tags:
  - astrotower
  script:
  # Compile our app
  - make PY=python3
  - make python PY=python3
  - make allExamples PY=python3
  - python3 test.py nocompile nopy nodoc ALL
  artifacts:
    paths:
    - External
    - Examples
    - Headers/*.h
    - ./*.so
    - Python/CosmoBolognaLib.py
    - Python/_CosmoBolognaLib.so