# Specify the docker image to use (only used if using docker runners)
# See: http://doc.gitlab.com/ee/ci/docker/using_docker_images.html
image: registry.gitlab.com/federicomarulli/cosmobolognalib 

# Try to compile CosmoBolognaLib
compile_cpp:
  script:
  # Compile our app
  - make
  - make allExamples
  artifacts:
    paths:
    - Headers/*.h
    - ./*.so
  
test:
  script:
  - ./test.py nocompile nopy nodoc ALL